version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./redis.conf:/app/redis.conf
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file: .env
  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    env_file: ./ai/.env
    ports:
      - "8000:5000"